baseurl = "https://example.com/"
title = "Whiteplain"
themesDir = "../../"
theme = "whiteplain"
languageCode = "ja"
# Disqus shortname
#disqusShortname = ""
# google analytics tracking id
#googleAnalytics = ""
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2017 Foo Bar"

[params]
  # Date format
  #dateFormat = "January 2, 2006"

# This is displayer in About page.
[params.author]
  name = "Foo Bar"

  # Gravatar or Abatar image
  #gravatar = "Gravatar email or MD5 Hash"
  #avatar = "/path/to/avatar"

  #twitter = "Twitter username"
  #facebook = "Facebook username"
  #googleplus = "Googleplus username"
  #instagram = "Instagram username"
  #tumblr = "Tumblr username"
  #flickr = "Flickr username"
  #reddit = "Reddit username"
  #linkedin = "Linkedin username"
  #slideshare = "Slideshare username"
  #github = "Github username"
  #gitlab = "Gitlab username"
  #bitbucket = "Bitbucket username"
  #stackoverflow = "Stackoverflow username"
  #jsfiddle = "Jsfiddle username"
  #codepen = "Codepen username"
  #deviantart = "Deviantart username"
  #behance = "Behance username"
  #dribbble = "Dribbble username"
  #wordpress = "Wordpress username"
  #medium = "Medium username"
  #foursquare = "Foursquare username"
  #xing = "Xing username"
  #quora = "Quora username"
  #youtube = "Youtube username"
  #vimeo = "Vimeo username"
  #whatsapp = "Whatsapp username"
  #skype = "Skype username"
  #snapchat = "Snapchat username"
  #pinterest = "Pinterest username"
  #telegram = "Telegram username"
  #vine = "Vine username"
  #email = "Your email"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[menu.main]]
  name = "Categories"
  weight = 1
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "Tags"
  weight = 2
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Archives"
  weight = 3
  identifier = "archives"
  url = "/archives/"
[[menu.main]]
  name = "About"
  weight = 4
  identifier = "about"
  url = "/about/"

[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
